version: "3.0"

services:
  wp:
    build: "."
    volumes:
      - ".:/var/www/html"
    ports:
      - "8080:8080"
    entrypoint: "sh"
    command: "bin/run.sh"
    working_dir: "/var/www/html"
  db:
    image: "mariadb"
    user: "mysql"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
volumes:
  db_data:
